version: "3.1"

services:
  mongo:
    image: mongo:5.0.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongoRootPassword
    ports:
      - 27017:27017
    volumes:
      - /data/db:/data/db
  mongo-express:
    image: mongo-express:0.54.0
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongoRootPassword
    links:
      - mongo
    ports:
      - "8081:8081"
    volumes:
      - /data/mongo-express:/data/mongo-express
  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: listen --forward-to host.docker.internal:3001/api/v1/stripe-webhook
    environment:
      - STRIPE_AUTH_SECRET_KEY=${STRIPE_AUTH_SECRET_KEY}
      - STRIPE_AUTH_PUBLIC_KEY=${STRIPE_AUTH_PUBLIC_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_DEVICE_NAME=${STRIPE_DEVICE_NAME}
