name: deploy staging node
on:
  push
  #  types: [push]
  # paths:
  #   - "node/**"
jobs:
  deploy-staging-node:
    #  if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./node
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "eu-west-2"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12.20.1"
      - uses: hmanzur/actions-aws-eb@v1.0.0
        with:
          command: "init --region ${{ secrets.AWS_DEFAULT_REGION }} --platform Node.js node-express-env-staging"
      - run: npm install --only=prod
      - run: npm run deploy:staging
